"""
Django settings for signature_project project.

Generated by 'django-admin startproject' using Django 3.1.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't(w+$(4k4jf4imwlikcy_+qfx1+=&j1adw%tzwph69&fwin$+f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['testapppjb0001.raloy.com.mx', 'localhost', '127.0.0.1']
ALLOWED_HOSTS=['*']
CSRF_TRUSTED_ORIGINS = [
    'https://dsign.raloy.com.mx',
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'motor_firmas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'signature_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'signature_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'ia-peter',
        'CLIENT': {
            'host': 'mongodb://admin_mongo:auPnlS4PIT058ZmWuU82@santiagoraloy.fortiddns.com:29910/ia-peter?authSource=admin'
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_TZ = True
STATIC_URL = '/static/'

# Configuración para guardar PDFs temporalmente
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Carpeta raíz de resguardo documental normal en Google Drive.
# Bajo esta raíz N8N debe mantener dos subcarpetas: "Formatos" y "PDFs".
DRIVE_ARCHIVE_ROOT_FOLDER_ID = os.environ.get(
    'DRIVE_ARCHIVE_ROOT_FOLDER_ID',
    '1sCj-iPiNtyitSHz5O2Mv3KSDGZiDDgf0',
)
DRIVE_FORMATOS_FOLDER_NAME = os.environ.get('DRIVE_FORMATOS_FOLDER_NAME', 'Formatos')
DRIVE_PDFS_FOLDER_NAME = os.environ.get('DRIVE_PDFS_FOLDER_NAME', 'PDFs')
DRIVE_PDFS_FOLDER_ID = os.environ.get('DRIVE_PDFS_FOLDER_ID', '')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Djongo 1.3.6 falla en producción al traducir algunas consultas de
# django_session. El portal solo guarda correos en sesión, así que usar cookies
# firmadas evita depender de MongoDB para login/admin y PDFs.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# FIRMX Classic API integration. Values can be overridden in production.
FIRMX_API_BASE_URL = os.environ.get(
    'FIRMX_API_BASE_URL',
    'https://stage.firmx.mobilender.mx/digisign/api/v1',
).rstrip('/')
FIRMX_API_KEY = os.environ.get('FIRMX_API_KEY', 'NKn4E8bW.0We4XYtyi5GHOf8lmHIdmEXbimb9Mdp1')
FIRMX_REQUEST_TIMEOUT = int(os.environ.get('FIRMX_REQUEST_TIMEOUT', '45'))

# --- MONKEY PATCH PARA DJONGO + PYMONGO 4+ / PYTHON 3.12 ---
# Corrige errores de compatibilidad y revela el error original en DatabaseError
try:
    import logging
    import traceback
    import collections
    
    # 0. Parche para collections (Python 3.10+)
    if not hasattr(collections, 'Iterable'):
        import collections.abc
        collections.Iterable = collections.abc.Iterable
        collections.Mapping = collections.abc.Mapping
        collections.MutableMapping = collections.abc.MutableMapping
        collections.Sequence = collections.abc.Sequence
        collections.Callable = collections.abc.Callable

    from djongo.database import DatabaseError as DjongoDatabaseError
    
    # 1. Parche global para PyMongo (evita que cualquier "if db:" falle)
    from pymongo.database import Database
    Database.__bool__ = lambda x: True
    
    # 2. Parche específico para Djongo DatabaseWrapper
    from djongo.base import DatabaseWrapper
    if not hasattr(DatabaseWrapper, '_patched'):
        original_close = DatabaseWrapper._close
        def patched_close(self):
            if self.connection is not None:
                with self.wrap_database_errors:
                    self.connection.client.close()
        DatabaseWrapper._close = patched_close
        DatabaseWrapper._patched = True

    # 3. Parche para Cursor: Revelar la causa real del DatabaseError y Logear a archivo
    from djongo.cursor import Cursor
    if not hasattr(Cursor, '_patched'):
        def make_patched_method(original_method_name):
            original_method = getattr(Cursor, original_method_name)
            def patched(self, *args, **kwargs):
                try:
                    return original_method(self, *args, **kwargs)
                except Exception as e:
                    # Capturamos TODO el error para verlo en un archivo
                    try:
                        with open('/tmp/djongo_error.log', 'a') as f:
                            f.write(f"\n--- ERROR EN {original_method_name.upper()} ---\n")
                            f.write(f"Exception: {type(e).__name__}: {str(e)}\n")
                            if hasattr(e, '__cause__') and e.__cause__:
                                f.write(f"Cause: {type(e.__cause__).__name__}: {str(e.__cause__)}\n")
                            f.write(traceback.format_exc())
                            f.write("-" * 30 + "\n")
                    except:
                        pass
                    
                    # Si es un DatabaseError sin mensaje, intentamos lanzar la causa original
                    if isinstance(e, DjongoDatabaseError) and not str(e):
                        if hasattr(e, '__cause__') and e.__cause__:
                            raise e.__cause__
                    raise e
            return patched

        Cursor.execute = make_patched_method('execute')
        Cursor.fetchone = make_patched_method('fetchone')
        Cursor.fetchmany = make_patched_method('fetchmany')
        Cursor.fetchall = make_patched_method('fetchall')
        Cursor._patched = True
        
except Exception as e:
    print(f"Error aplicando parches de Djongo: {e}")
