# Generated by Django 3.1.12 on 2026-03-31 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoFirma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('token_acceso', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pdf_path', models.CharField(max_length=500)),
                ('firmantes', models.JSONField()),
                ('indice_actual', models.IntegerField(default=1)),
                ('status', models.CharField(default='PROCESSING', max_length=50)),
            ],
        ),
    ]
