# Generated by Django 3.1.12 on 2026-04-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesofirma',
            name='summary_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procesofirma',
            name='view_info',
            field=models.CharField(default='file', max_length=20),
        ),
    ]
