# Generated by Django 3.1.12 on 2026-04-09 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0002_auto_20260408_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesofirma',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='procesofirma',
            name='owner_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
