# Generated by Django 3.1.12 on 2026-04-09 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0003_auto_20260409_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorioFirmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('puesto', models.CharField(max_length=200)),
                ('iniciales', models.CharField(max_length=10)),
                ('firma_base64', models.TextField()),
                ('pin_hash', models.CharField(max_length=255)),
                ('acepto_terminos', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('reset_token', models.UUIDField(blank=True, null=True)),
                ('reset_token_expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
