# Generated by Django 3.1.12 on 2026-04-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0004_directoriofirmas'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
