# Generated by Django 3.1.12 on 2026-04-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0005_otplogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('configuracion_dashboard', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
