# Generated by Django 3.1.12 on 2026-04-10 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0006_administradorportal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('doc_id', models.CharField(max_length=200)),
                ('owner_email', models.CharField(max_length=200)),
                ('drive_folder_id', models.CharField(max_length=200)),
                ('view_info', models.CharField(default='file', max_length=50)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('intencion', models.TextField(blank=True, null=True)),
                ('variables', models.JSONField(default=list)),
                ('firmantes_config', models.JSONField(default=list)),
                ('usuarios_permitidos', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='procesofirma',
            name='dir_drive',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='procesofirma',
            name='document_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='procesofirma',
            name='exec_mode',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='procesofirma',
            name='valores_capturados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
