# Generated by Django 3.1.12 on 2026-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0007_auto_20260409_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaformulario',
            name='formato_folio',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
