# Generated by Django 3.1.12 on 2026-04-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0008_plantillaformulario_formato_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaformulario',
            name='carpeta_firmados_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
