# Generated by Django 3.1.12 on 2026-04-13 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0009_plantillaformulario_carpeta_firmados_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaDominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=100, unique=True)),
                ('drive_folder_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
