# Generated by Django 3.1.12 on 2026-04-13 22:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0010_carpetadominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPDFUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('drive_file_id', models.CharField(max_length=200)),
                ('owner_email', models.CharField(max_length=200)),
                ('archivo_local', models.CharField(blank=True, max_length=500, null=True)),
                ('enviado_a_firma', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
