# Generated by Django 4.1.13 on 2026-05-14 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0011_documentopdfusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('reference_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'signature_notifications',
            },
        ),
        migrations.AddField(
            model_name='administradorportal',
            name='es_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directoriofirmas',
            name='notificar_celular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directoriofirmas',
            name='permisos_portal',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='directoriofirmas',
            name='tecnico_asignado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='directoriofirmas',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administradorportal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carpetadominio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='directoriofirmas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentopdfusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='otplogin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plantillaformulario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procesofirma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
