# Generated by Django 4.1.13 on 2026-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_firmas', '0012_signaturenotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignaturesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=255, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
                ('notification_enabled', models.BooleanField(default=False)),
                ('notified_to_mobile', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'signatures_master',
            },
        ),
    ]
